source "https://rubygems.org"

gem "jekyll", "~> 4.2.0"
gem "jekyll-feed", "~> 0.12"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-seo-tag", "~> 2.6"
gem "jekyll-paginate", "~> 1.1"
gem "jekyll-archives", "~> 2.2"
gem "jekyll-sass-converter", "~> 2.1"
gem "webrick", "~> 1.7"
gem "csv"
gem "base64"
gem "bigdecimal"
