name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 2 * * 1'  # Weekly schedule at 2 AM every Monday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - name: Install dependencies
      run: |
        bundle install
        npm install

    - name: Build site with Jekyll
      run: bundle exec jekyll build

    - name: Run HTMLProofer to check for broken links
      run: |
        gem install html-proofer
        bundle exec htmlproofer ./_site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        keep_files: false

  code_quality:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3

    - name: Run ESLint for JavaScript
      run: npx eslint .

    - name: Run RuboCop for Ruby
      run: bundle exec rubocop

    - name: Check for Duplicate Code
      uses: codeclimate/codeclimate@v1.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        exit-code: 0

  report:
    runs-on: ubuntu-latest
    needs: [build, code_quality]

    steps:
    - name: Post build status
      run: echo "Build and code quality checks completed successfully"
