name: Scheduled Code Quality Check

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight UTC

jobs:
  code_quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Install Rubocop for linting
      run: gem install rubocop

    - name: Run Rubocop to check code quality
      run: rubocop .
